Repository Vinay-Khanagavi/Cyberbear.github.io, pull requests merged in 2024-10, with the labels that each got.

#38 Create greeting.yml
  .github/workflows/greeting.yml
Labels: gssoc-ext, level1, hacktoberfest

#46 Enhancements, fixes and UI/UX Improvements ISSUE#8
  main/level_1/amazon.html
  main/level_1/js/end.js
  main/level_1/question.html
  main/level_1/save_game.html
Labels: hacktoberfest-accepted

#63 fix issue: #52
  main/level_4/level_4/match_the_following.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#80 Added an MIT License
  LICENSE
Labels: hacktoberfest-accepted

#71 Fixed level 2 page.
  main/level_2/amazon.html
  main/level_2/question.html
  main/level_2/save_game.html
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, priority:high

#78 Updated the readme file.
  CONTRIBUTING.md
  README.md
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#83 Fixing level 3 page + logic improvement in all the levels.
  main/level_1/question.html
  main/level_2/js/end.js
  main/level_2/question.html
  main/level_3/amazon.html
  main/level_3/js/end.js
  main/level_3/question.html
  main/level_3/save_game.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, priority:high

#87 Fixed bug in level4 where same option can be selected
  main/level_4/level_4/match_the_following.html
  main/level_4/level_4/script.js
Labels: gssoc-ext, level2, hacktoberfest-accepted, priority:high

#116 Incorrect redirection of Back Button as well as page invalid redirection
  main/level_1/phishing_awareness.html
  main/level_2/phishing_awareness.html
  main/level_3/phishing_awareness.html
Labels: Changes required

#125 Implemented deduction of points for wrong answer in all levels
  main/level_1/question.html
  main/level_2/question.html
  main/level_3/question.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, Active

#131 Added cyber quiz app with gemini
  cyber-quiz-app/.eslintrc.json
  cyber-quiz-app/.gitignore
  cyber-quiz-app/components.json
  cyber-quiz-app/next.config.js
  cyber-quiz-app/package-lock.json
  cyber-quiz-app/package.json
  cyber-quiz-app/postcss.config.js
  cyber-quiz-app/public/logo.ico
  cyber-quiz-app/public/next.svg
  cyber-quiz-app/public/vercel.svg
  cyber-quiz-app/src/app/favicon.ico
  cyber-quiz-app/src/app/globals.css
  cyber-quiz-app/src/app/layout.tsx
  cyber-quiz-app/src/app/page.tsx
  cyber-quiz-app/src/categories.ts
  cyber-quiz-app/src/components/ui/button.tsx
  cyber-quiz-app/src/lib/ai.ts
  cyber-quiz-app/src/lib/common.ts
  cyber-quiz-app/src/lib/utils.ts
  cyber-quiz-app/tailwind.config.js
  cyber-quiz-app/tailwind.config.ts
  cyber-quiz-app/tsconfig.json
Labels: gssoc-ext, level3, hacktoberfest-accepted

#130 added home buttons in all levels
  main/level_1/hint.html
  main/level_1/hint_2.html
  main/level_1/sam_message.html
  main/level_1/sam_message_2.html
  main/level_1/sam_message_3.html
  main/level_1/sam_message_4.html
  main/level_2/hint_2.html
  main/level_2/sam_message.html
  main/level_2/sam_message_2.html
  main/level_2/sam_message_3.html
  main/level_2/sam_message_4.html
Labels: gssoc-ext, level2, hacktoberfest-accepted, priority:low, Active

#147 #144 -Fix: Changed button to correctly reflect state during Autoplay
  main/level_1/phishing_animated_video.html
  main/level_2/phishing_animated_video.html
  main/level_3/phishing_animated_video.html
Labels: gssoc-ext, level2, hacktoberfest

#153 screen height issue in levels solved
  css/index-level1.css
Labels: good first issue, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted, Changes required

#151 fix video responsiveness on level 1, 2 and 3
  main/level_1/phishing_animated_video.html
  main/level_2/phishing_animated_video.html
  main/level_3/phishing_animated_video.html
Labels: Changes required

#158 deleted unnecessary homepage files
  homepage.html
  homepage1.css
  homepage1.html
Labels: hacktoberfest-accepted
